name: Deploy the backend

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v2

      # Step 2: Docker login
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ranjeetvit/node-bun-app:${{ github.sha }}

      # Step 4: Deploy to AWS EC2 Instance
      - name: Deploy to Backend AWS EC2 Instance
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ec2-user@${{ secrets.AWS_EC2_PUBLIC_IP }} -t "
            docker stop user_backend || true && \
            docker rm user_backend || true && \
            docker system prune -af --volumes && \
            docker run --name user_backend -d -p 8080:8080 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            ranjeetvit/todo-app-backend:${{ github.sha }}"


